# -*- coding: utf-8 -*-
"""Exercise_1_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18r_cQPv_A5xxkrNiZoj_O1Ay6awFUel2

### 1. Write a program to iterate the first 10 numbers and in each iteration, print the sum of the current and previous number.
"""

# %%writefile 1.py
for i in range(1 , 11):
  print(f'Sum of the Current and the Previous Number is { i + i-1}')

"""### 2. Write a program to accept a string from the user and display characters that are present at an even index number.

"""

# %%writefile 2.py
string =input('Enter the string here :')
s = ''
for i in range(len(string)):
  if i%2==0:
    pass
  else:
    s += string[i]
print(s)

"""### 3. Iterate the given list of numbers and print only those numbers which are divisible by 5"""

# %%writefile 3.py
l = [2,3,5,2,10,4,56,100]
for i in range(len(l)):
  if l[i]% 5 == 0:
    print(f'the Number {l[i]} is divisible by 5')

"""### 4. Write a program to check if the given number is a palindrome number."""

# %%writefile 4.py
# An integer is a palindrome when it reads the same backward as forward.
n = input('enter the number here :')
if n == n[::-1]:
  print('Numbers is Palindrome')
else:
  print('Not a Palindrome Number')

"""### 5. Given a two list of numbers, write a program to create a new list such that the new list should contain odd numbers from the first list and even numbers from the second list."""

# %%writefile 5.py
l =[1,2,3,4,5]
l1 = [4,5,7,8,9]
new_l = []
for i in l:
  if i%2 != 0:
    new_l.append(i)
for j in l1 :
  if j%2 == 0:
    new_l.append(j)


print(new_l)

"""### 6. Write a Program to extract each digit from an integer in the reverse order."""

# %%writefile 6.py
n = int(input('enter the number here :'))
while(n != 0):
  p = n%10
  n = n//10
  print(p , end = '')

"""### 7. Print multiplication table form 1 to 10"""

# %%writefile 7.py
for i in range(1 , 11):
  for j in range(1 , 11):
    print(f' {i} * {j} = {i*j}')
  print(sep = '\t')

"""### 8. Write a program to print downward Half-Pyramid Pattern with Star (asterisk)

"""

# %%writefile 8.py
for i in range(5):
  for j in range(5):
    if j >= i :
      print("*" ,end = '')
    else:
      pass
  print("\r") # end line after each row

